language: perl
perl:
  - '5.20'
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - '5.10'
  - 5.8
before_install:
  - perlbrew install-cpanm -f;  cpanm Carton
install:
  - '(carton install && perl Makefile.PL) || cat ~/.cpanm/build.log'
script:
  - 'make && carton exec "prove -b -v"'
sudo: false
