language: perl
perl:
  - 5.22
  - '5.20'
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - '5.10'
  - 5.8
before_install:
  - perlbrew install-cpanm -f;  cpanm Carton
install:
#  - '(perl maint/carton_install_with_configuredeps.pl) || cat ~/.cpanm/build.log'
#  - 'cpanm -L local -nq --installdeps --with-recommends --with-suggests .'
  - 'carton install'
  - 'carton exec "perl ./Makefile.PL"'
script:
  - 'carton exec "make"'
  - 'carton exec "prove -b -v"'
sudo: false
