language: perl
perl:
  - 5.22
  - '5.20'
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - '5.10'
  - 5.8
before_install:
  - perlbrew install-cpanm -f;  cpanm Carton
install:
  - '(perl maint/carton_install_with_configuredeps.pl) || cat ~/.cpanm/build.log'
  - 'carton exec "perl -MCPAN::Config" 2>&1 1>/dev/null || (echo y;echo o conf prerequisites_policy follow;echo o conf commit)| carton exec "cpan"'
  - 'carton exec "perl Makefile.PL"'
script:
  - 'make'
  - 'carton exec "prove -b -v"'
sudo: false
