language: perl
perl:
  - 5.22
  - '5.20'
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - '5.10'
  - 5.8
before_install:
  - perlbrew install-cpanm -f;  cpanm Carton
install:
  - '(perl maint/carton_install_with_configuredeps.pl) || cat ~/.cpanm/build.log'
  - 'carton exec "perl ./Build.PL"'
script:
  - 'carton exec "./Build"'
  - 'carton exec "prove -b -v"'
sudo: false
